"""Changes user Model

Revision ID: 0dea353d2872
Revises: 1f612579b003
Create Date: 2024-03-13 19:00:08.612751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dea353d2872'
down_revision = '1f612579b003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
