"""Added a delted_at in db models

Revision ID: 1f612579b003
Revises: 3288ca827f3b
Create Date: 2024-03-13 18:43:22.391347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f612579b003'
down_revision = '3288ca827f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('producent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producent', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('producer')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
