"""Change admin with email_confirmed

Revision ID: 6699fccb6e2c
Revises: eeda4782ac62
Create Date: 2024-02-22 14:18:18.324243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6699fccb6e2c'
down_revision = 'eeda4782ac62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed_at')

    # ### end Alembic commands ###
