"""Create customers db

Revision ID: 79e43cd9c89a
Revises: b41346ac4f8f
Create Date: 2024-02-20 13:29:43.927705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79e43cd9c89a'
down_revision = 'b41346ac4f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('adress', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('adress', sa.String(length=120), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('adress')
        batch_op.drop_column('last_name')

    op.drop_table('customer')
    # ### end Alembic commands ###
