"""Changes user Model

Revision ID: c08e6737a22c
Revises: 0dea353d2872
Create Date: 2024-03-13 19:08:34.146021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c08e6737a22c'
down_revision = '0dea353d2872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
